cache_length: 600
debug: true
timeout: 10
user_agent: Package Control Default Channel Server
http_cache: true
http_cache_length: 5184000
install_prereleases: true
downloader_precedence: 
    windows: [wininet, oscrypto]
    osx: [oscrypto, urllib, curl]
    linux: [oscrypto, urllib, curl, wget]
http_basic_auth:
    api.github.com: ["wbond", "Use config.read_secret('github_access_token_USERNAME')"]
    gitlab.com: ["wbond", "Use config.read_secret('gitlab_access_token_USERNAME')"]
    api.bitbucket.org: ["wbond", "Use config.read_secret('bitbucket_app_password_USERNAME')"]
